# Generated by Django 4.0.3 on 2022-07-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='phone',
            new_name='deadline',
        ),
    ]
